name: creditcard_fraud_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - scikit-learn
    - mlflow
    - dagshub
    - matplotlib
    - seaborn
    - python-dotenv